### ISSUE TITLE
Can add support kirikiri of "Imouto Kairaku Och" of extract ?

### ISSUE THREAD

**Issue by sum2012** [Kerisa/ExtractGames#2]
@Kerisa
Can add support kirikiri of "Imouto Kairaku Och" of extract ?
https://vndb.org/v24435
The game exe would crash while dumping.

**Comment by Kerisa** [comment]
Try out [this](https://github.com/Kerisa/ExtractGames/releases/tag/v1.0)

**Comment by sum2012** [comment]
No crash now .thanks.
